# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
git clone https://github.com/gtfierro/patentprocessor
cd patentprocessor
sudo pip install --upgrade setuptools distribute
sudo pip install -r requirements.txt
cd lib
wget https://s3.amazonaws.com/fungpatdownloads/geolocation_data.7z
7zr x geolocation_data.7z
sudo chmod -R 777 /home/vagrant/patentprocessor
echo 'create database patentgrant; create database patentapp' | mysql -u root
cat > /home/vagrant/patentprocessor/lib/alchemy/config.ini << EOF
[global]
database = mysql
echo = False

[mysql]
host = 
user = root
password = 
grant-database = patentgrant
application-database = patentapp

[assignee]
threshold = 0.90

[location]
database = geolocation_data.sqlite3
path = lib
commit_frequency = 10000

[lawyer]
threshold = 0.9

[parse]
# if not specified, defaults to 0 (commits after all rows added)
commit_frequency = 1000
EOF
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu13"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory",8192]
  end


  #config.vm.network :public_network, :bridge => 'eth0: Ethernet'
  #config.vm.network :forwarded_port, guest: 5000, host: 5000

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  config.vm.provision :puppet
  config.vm.provision "shell", inline: $script
end
