alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_assignees` (`num_assignees`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_inventors` (`num_inventors`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_inventors_group` (`num_inventors_group`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_assignees_group` (`num_assignees_group`);
-- alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_subsection_id` (`subsection_id`);
-- alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_patents_group` (`num_patents_group`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_num_patents` (`num_patents`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_group_id` (`group_id`);
alter table `{{params.reporting_database}}`.`cpc_current` add index `ix_cpc_current_subgroup_id` (`subgroup_id`);
alter table `{{params.reporting_database}}`.`examiner` add index `ix_examiner_name_first` (`name_first`);
alter table `{{params.reporting_database}}`.`examiner` add index `ix_examiner_name_last` (`name_last`);
alter table `{{params.reporting_database}}`.`examiner` add index `ix_examiner_role` (`role`);
alter table `{{params.reporting_database}}`.`examiner` add index `ix_examiner_group` (`group`);
alter table `{{params.reporting_database}}`.`examiner` add index `ix_examiner_persistent_examiner_id` (`persistent_examiner_id`);