alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`pctdata` add index `ix_pctdata_102_date` (`102_date`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`pctdata` add index `ix_pctdata_date` (`date`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`pctdata` add index `ix_pctdata_doc_number` (`doc_number`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`pctdata` add index `ix_pctdata_doc_type` (`doc_type`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`pctdata` add index `ix_pctdata_371_date` (`371_date`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`usapplicationcitation` add index `ix_usapplicationcitation_cited_application_id` (`cited_application_id`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspatentcitation` add index `ix_uspatentcitation_cited_patent_id` (`cited_patent_id`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass_patent_year` add index `ix_uspc_current_mainclass_patent_year_num_patents`(`num_patents`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add index `ix_uspc_current_mainclass_num_patents` (`num_patents`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add fulltext index `fti_uspc_current_mainclass_mainclass_title` (`mainclass_title`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add index `ix_uspc_current_mainclass_mainclass_title` (`mainclass_title`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add index `ix_uspc_current_mainclass_num_assignees` (`num_assignees`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add index `ix_uspc_current_mainclass_num_inventors` (`num_inventors`);
alter table `PatentsView_{{ dag_run.logical_date | ds_nodash }}`.`uspc_current_mainclass` add index `ix_uspc_current_mainclass_mainclass_id` (`mainclass_id`);