version: '3'
services:
  mydumper_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - S3_ACCESS_KEY_ID
     - S3_SECRET_ACCESS_KEY
     - S3_ENDPOINT_URL
     - S3_BUCKET
    volumes:
     - {LOCAL_PATH}:/DatabaseBackups
     - {LOCAL_PATH}:/project
    command:
      - mydumper