services:
  mydumper_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - S3_ACCESS_KEY_ID
     - S3_SECRET_ACCESS_KEY
     - S3_ENDPOINT_URL
     - S3_BUCKET
    volumes:
     - /home/ec2-user/PipelineData/DatabaseBackups:/DatabaseBackups
     - /home/ec2-user/PatentsView-DB:/project
     - ./mydumper.cnf:/etc/mydumper.cnf
    command: mydumper --verbose=3
